

### this is for deployment of nginx

--- 
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: trail-deploy
  labels: 
    app: web
spec: 
  minReadySeconds: 10
  replicas: 10 
  selector: 
    matchLabels: 
      app: web
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 40%
      maxUnavailable: 40%
  template: 
    metadata: 
      name: web
      labels: 
        app: web
        version: 'v1.0'
    spec: 
      containers: 
        - name: nginx
          image: nginx   
          ports: 
            - containerPort: 80
              protocol: TCP
           



--- 
apiVersion: v1 
kind: Service
metadata: 
  name: deploy-svc 
  labels: 
    app: web
spec: 
  type: NodePort
  selector: 
    app: web 
  ports: 
    - name: nginx
      nodePort: 31000
      targetPort: 80
      port: 80