# manifesto for replicaset with svc for apache to  expose outside 

--- 
apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
  name: httpd-rs
  labels: 
    env: xxxx
spec: 
  minReadySeconds: 10
  replicas: 5
  selector: 
    matchLabels: 
      app: httpd 
  template: 
    metadata: 
      name: httpd-rs
      labels: 
        app: httpd 
        env: dev 
        version: v3.4.0
    spec: 
      containers: 
        - name: httpd 
          image: httpd
          ports: 
            - containerPort: 80    




--- 
apiVersion: v1 
kind: Service
metadata: 
  name: apache-svc 
spec: 
  type: NodePort
  selector: 
    app: httpd 
  ports: 
    - port: 80 
      targetPort: 80    
      nodePort: 30000
