### this is for spc replicaset and svc to expose outside
--- 

apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
  name: spc-rs
  labels: 
    env: xxxx
spec: 
  minReadySeconds: 10
  replicas: 5
  selector: 
    matchLabels: 
      app: spc
  template: 
    metadata: 
      name: spc
      labels: 
        app: spc 
        env: dev 
        version: v3.4.0
    spec: 
      restartPolicy: Always
      containers: 
        - name: spc 
          image: sangamesh98/docker2024
          ports: 
            - containerPort: 8080   



--- 
apiVersion: v1 
kind: Service
metadata: 
  name: spc-svc
spec: 
  type: NodePort
  selector: 
    app: spc
  ports: 
    - port: 8080
      targetPort: 8080    
      nodePort: 31000
      name: spc 
