# this is for service with replicaset manifesto
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels: 
    urikey: timepass
spec: 
  minReadySeconds: 10
  replicas: 5
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels:
        app: nginx
        version: 'v1.0'
    spec: 
      containers:
        - name: nginx
          image: nginx
          ports: 
            - containerPort: 80



--- 
apiVersion: v1 
kind: Service
metadata: 
  name: nginx-svc 
spec: 
  selector: 
    app: nginx
  ports: 
    - name: nginx-svc
      port: 80 
      targetPort: 80                    