### playbook for installing 'tree'
--- 
- name: install tree
  hosts: all
  become: yes
  tasks:
    - name: install tree on ubuntu
      ansible.builtin.apt:
        name: tree
        update_cache: yes
        state: present