--- 
# this is for multi init container manifesto


apiVersion: v1
kind: Pod 
metadata: 
  name: init
spec: 
  restartPolicy: OnFailure
  initContainers: 
    - name: init1 
      image: alpine 
      args: 
        - sleep
        - 10s  
    - name: init2 
      image: alpine 
      args: 
        - sleep
        - 10s 
    - name: init3 
      image: alpine 
      args: 
        - sleep
        - 10s    
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 1000m
          memory: 0.5Gi
    - name: nginx1 
      image: nginx    
      resources: 
        limits: 
          cpu: 1000m
          memory: 0.5Gi  