
# manifesto for labels to pod

--- 
apiVersion: v1
kind: Pod 
metadata: 
  name: labels
  labels: 
    env: dev
    app: sss 
    version: '1.0'
spec: 
  containers:
    - name: nginx
      image: nginx    
      resources:
        limits:
          cpu: 500m
          memory: 512Mi