FROM  amazoncorretto:17-alpine3.17-jdk
RUN wget "https://khajareferenceapps.s3.ap-south-1.amazonaws.com/spring-petclinic-3.2.0-SNAPSHOT.jar"
LABEL author="sangu"
LABEL project="practise"
EXPOSE 8080
CMD [ "java", "-jar", "spring-petclinic-3.2.0-SNAPSHOT.jar" ]