FROM amazoncorretto:17-alpine3.17-jdk
 # download the file 
ADD --chown=spc:spc https://khajareferenceapps.s3.ap-south-1.amazonaws.com/spring-petclinic-3.2.0-SNAPSHOT.jar /spc/spring-petclinic-3.2.0-SNAPSHOT.jar
LABEL author="sangu"
LABEL project="practise"
WORKDIR /spc 
EXPOSE 8080
CMD [ "java", "-jar", "spring-petclinic-3.2.0-SNAPSHOT.jar" ]
  #creating user and usergroup
RUN addgroup -g 1000 spc $$ adduser -h "/spc" -u 1000 -G spc -s /bin/bash D spc 
  # switching to user spc 
USER spc
