
### manifesto for creating deployment with namespace
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: trail-ns
  labels: 
    app: nginx
  namespace: dev 
spec: 
  minReadySeconds: 10
  progressDeadlineSeconds: 30
  replicas: 4
  selector:
    matchLabels: 
      app: nginx
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      name: ns 
      labels: 
        app: nginx
        env: dev 
        version: 'v1.0'
    spec: 
      containers: 
        - name: nginx
          image: nginx
          ports: 
            - containerPort: 80




--- 
apiVersion: v1 
kind: Service
metadata: 
  name: nginx-svc
  namespace: dev 
spec: 
  selector:
    app: nginx  
  ports:
    - name: nginx
      port: 80
      targetPort: 80  




--- 
apiVersion: v1 
kind: Namespace
metadata: 
  name: dev 







