---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lt-creader
rules:
  - apiGroups: 
      - "*"
    resources:
      - "\*"
    verbs:
      - get
      - list
      - watch