apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ltadminrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lt-admin
subjects:
  - apiGroup: "rbac.authorization.k8s.io"
    kind: User
    name: johndoe
  - apiGroup: ""
    kind: ServiceAccount
    name: admin-sa