---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lt-admin
  namespace: dev
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - "\*"
    verbs:
      - "\*"

