FROM mcr.microsoft.com/dotnet/sdk:7.0
EXPOSE 5000

ARG DOWNLOAD_URL=https://github.com/nopSolutions/nopCommerce/releases/download/release-4.70.2/nopCommerce_4.70.2_NoSource_linux_x64.zip

ADD ${DOWNLOAD_URL} /app/nopCommerce_4.70.2_NoSource_linux_x64.zip

RUN apt update && \
    apt install unzip -y && \
    cd /app && \
    unzip nopCommerce_4.70.2_NoSource_linux_x64.zip

CMD ["dotnet", "Nop.Web.dll", "--urls", "http://0.0.0.0:5000"]